fix bug
Hi,
In the last test code has this error. I've corrected this with this
changes but maybe I went in a wrong way. Please check this.

Thanks
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/radix/radix.py", line 426,
in add
node = self._tree4.add(prefix)
File "/usr/local/lib/python2.7/dist-packages/radix/radix.py", line 124,
in add
while node.bitlen < bitlen or node._prefix.addr is None:
AttributeError: 'NoneType' object has no attribute 'addr'